-- Create the USERS table (Oracle 11g compatible)
CREATE TABLE CYBER.USERS (
    ID NUMBER(10) NOT NULL PRIMARY KEY,
    USERNAME VARCHAR2(50) NOT NULL UNIQUE,
    EMAIL VARCHAR2(100) NOT NULL UNIQUE,
    PASSWORD_HASH VARCHAR2(255) NOT NULL,
    ROLE VARCHAR2(20) DEFAULT 'User' NOT NULL,
    IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL, -- 1 for true, 0 for false
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Create Sequence for auto-increment
CREATE SEQUENCE CYBER.USERS_SEQ START WITH 1 INCREMENT BY 1;

-- Create Trigger to handle auto-increment on insert
CREATE OR REPLACE TRIGGER CYBER.USERS_BIR
BEFORE INSERT ON CYBER.USERS
FOR EACH ROW
BEGIN
    IF :new.ID IS NULL THEN
        SELECT CYBER.USERS_SEQ.NEXTVAL INTO :new.ID FROM DUAL;
    END IF;
END;


-- Optional: Create an index on email for faster lookups
CREATE INDEX CYBER.IDX_USERS_EMAIL ON CYBER.USERS(EMAIL);

-- Insert a test user
INSERT INTO CYBER.USERS (USERNAME, EMAIL, PASSWORD_HASH, ROLE, IS_ACTIVE)
VALUES ('admin', 'admin@cyber.com', 'hashed_password_placeholder', 'Admin', 1);

COMMIT;
