ALTER TABLE process_instances ADD COLUMN IF NOT EXISTS total_cost NUMERIC DEFAULT 0;
ALTER TABLE process_history ADD COLUMN IF NOT EXISTS step_cost NUMERIC DEFAULT 0;
ALTER TABLE process_history ADD COLUMN IF NOT EXISTS time_spent_hours NUMERIC DEFAULT 0;
