using System;
using System.Collections.Generic;

namespace Cyber.Models;

public class JournalEntry
{
    public string Id { get; set; } = Guid.NewGuid().ToString();
    public string EntryNumber { get; set; } = string.Empty; // Generated by System
    public DateTime EntryDate { get; set; } = DateTime.Now;
    public string Description { get; set; } = string.Empty;
    public string? Reference { get; set; }
    public string Status { get; set; } = "DRAFT";
    public decimal TotalDebit { get; set; }
    public decimal TotalCredit { get; set; }
    public string? CreatedBy { get; set; }
    public DateTime CreatedAt { get; set; } = DateTime.Now;
    public DateTime? PostedAt { get; set; }
    public DateTime? VoidedAt { get; set; }

    public List<JournalLine> Details { get; set; } = new List<JournalLine>();
}

public class JournalLine
{
    public string Id { get; set; } = Guid.NewGuid().ToString();
    public string JournalEntryId { get; set; } = string.Empty;
    public int LineNumber { get; set; }
    public string AccountCode { get; set; } = string.Empty;
    public string? AccountName { get; set; } // Read-only helper
    public string Description { get; set; } = string.Empty; // Line description
    public decimal DebitAmount { get; set; }
    public decimal CreditAmount { get; set; }
}
